name: todo_app
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  webview_flutter: 4.4.1
  http: ^1.2.2
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.3
  image: ^4.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true